/**
 * Tooltip formatters for the ECharts charts.
 *
 * ECharts inserts a formatter's return value as HTML without escaping it, so
 * anything that comes from data (player names, round labels) must go through
 * escapeHtml. `marker` is HTML generated by ECharts itself and is left as is.
 */

import { escapeHtml } from '$lib/utils/safeHtml'
import { formatScore } from '$lib/utils/gw'

export interface MultiPlayerTooltipItem {
	marker: string
	seriesName: string
	value: number
	name: string
}

/** Round label, then the top 10 players for that round by score. */
export function multiPlayerTooltip(items: MultiPlayerTooltipItem[]): string {
	const first = items[0]
	if (!first) return ''
	const lines = [...items]
		.sort((a, b) => b.value - a.value)
		.slice(0, 10)
		.map((item) => `${item.marker} ${escapeHtml(item.seriesName)}: ${formatScore(item.value)}`)
	return `${escapeHtml(first.name)}<br/>${lines.join('<br/>')}`
}
