import { describe, expect, it } from 'vitest'
import { multiPlayerTooltip, type MultiPlayerTooltipItem } from '../tooltips'

const item = (seriesName: string, value: number, name = 'Round 1'): MultiPlayerTooltipItem => ({
	marker: '<span class="marker"></span>',
	seriesName,
	value,
	name
})

describe('multiPlayerTooltip', () => {
	it('returns an empty string with no items', () => {
		expect(multiPlayerTooltip([])).toBe('')
	})

	it('lists players by score, highest first', () => {
		const html = multiPlayerTooltip([item('low', 10), item('high', 30), item('mid', 20)])
		const order = ['high', 'mid', 'low'].map((name) => html.indexOf(name))
		expect(order).toEqual([...order].sort((a, b) => a - b))
	})

	it('shows at most 10 players', () => {
		const items = Array.from({ length: 12 }, (_, i) => item(`player${i}`, i))
		expect(multiPlayerTooltip(items).split('<br/>')).toHaveLength(11)
	})

	it('escapes player names and round labels', () => {
		const html = multiPlayerTooltip([item('<img src=x onerror=alert(1)>', 5, '<b>Round</b>')])
		expect(html).not.toContain('<img')
		expect(html).not.toContain('<b>')
		expect(html).toContain('&lt;img src=x onerror=alert(1)&gt;')
		expect(html).toContain('&lt;b&gt;Round&lt;/b&gt;')
	})

	it('keeps the marker HTML generated by ECharts', () => {
		expect(multiPlayerTooltip([item('player', 5)])).toContain('<span class="marker"></span>')
	})
})
